actionTypes = { 
    INCREMENT_COUNTER :'INCREMENT_COUNTER',
    DECREMENT_COUNTER : 'DECREMENT_COUNTER',
    CHECK_ITEM : 'CHECK_ITEM',
    CKECK_ALL_ITEMS : 'CKECK_ALL_ITEMS',
    CALCULATE_TOTAL: 'CALCULATE_TOTAL',
    DELETE_ITEM: 'DELETE_ITEM',
    CHECK_PAYMENT: 'CHECK_PAYMENT',
    CHANGE_DELIVERY_TYPE: 'CHANGE_DELIVERY_TYPE',
}